-- Personal Finance and Budget Management System Database Schema (Optimized for Flask/PyMySQL API)

CREATE DATABASE IF NOT EXISTS personal_finance;
USE personal_finance;

-- Set character set and collation for broader character support
ALTER DATABASE personal_finance
CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- 1. User table (Authentication and core identity)
CREATE TABLE user (
    user_id VARCHAR(50) PRIMARY KEY, -- Used as the FK identifier in all other tables
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL, -- Stores bcrypt hash from werkzeug.security
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- 2. Preferences table (User settings, one-to-one with user)
CREATE TABLE preferences (
    user_id VARCHAR(50) PRIMARY KEY, -- Using user_id as the primary key since it's a 1:1 relationship
    currency VARCHAR(10) DEFAULT 'USD',
    theme VARCHAR(20) DEFAULT 'light',
    notifications BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
);


-- 3. Transaction table (Core financial movements)
CREATE TABLE transaction (
    transaction_id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    type ENUM('expense', 'income') NOT NULL,
    date DATE NOT NULL,
    category VARCHAR(50),
    description TEXT,
    receipt_data LONGTEXT, -- Stores base64 encoded image or URL
    FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE,
    INDEX idx_user_type (user_id, type)
);


-- 4. Budget table (Allocated spending limits)
CREATE TABLE budget (
    budget_id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    category VARCHAR(50) NOT NULL,
    amount DECIMAL(15, 2) NOT NULL,
    period ENUM('monthly', 'yearly', 'weekly', 'one-time') NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    is_exceeded BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE,
    INDEX idx_user_period (user_id, period)
);



-- 5. Goal table (Savings and financial targets)
CREATE TABLE goal (
    goal_id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    name VARCHAR(100) NOT NULL,
    target_amount DECIMAL(15, 2) NOT NULL,
    current_amount DECIMAL(15, 2) DEFAULT 0,
    deadline DATE,
    FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE,
    INDEX idx_user_deadline (user_id, deadline)
);


-- 6. Report table (Stored, complex analysis results)
CREATE TABLE report (
    report_id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL, -- e.g., 'monthly_summary', 'tax_report'
    data LONGTEXT, -- Stores large JSON string generated by the API
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE,
    INDEX idx_user_type (user_id, type)
);


-- 7. Notification table (User-facing alerts)
CREATE TABLE notification (
    notification_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    content TEXT NOT NULL,
    type ENUM('info', 'alert', 'budget_exceeded', 'goal_achieved') NOT NULL,
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE,
    INDEX idx_user_read (user_id, is_read)
);


-- 8. FinancialOverview table (Pre-calculated/Cached financial summary)
CREATE TABLE financial_overview (
    overview_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50) UNIQUE NOT NULL, -- Ensures only one overview per user
    total_income DECIMAL(15, 2) DEFAULT 0,
    total_expenses DECIMAL(15, 2) DEFAULT 0,
    net_worth DECIMAL(15, 2) DEFAULT 0,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
);


-- 9. Insight table (System-generated financial tips and observations)
CREATE TABLE insight (
    insight_id INT AUTO_INCREMENT PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    type VARCHAR(50), -- e.g., 'spending_habit', 'saving_tip'
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
);

-- 10. Reminder table (User-defined financial reminders)
CREATE TABLE reminder (
    reminder_id VARCHAR(50) PRIMARY KEY,
    user_id VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(50),
    description TEXT,
    amount DECIMAL(15, 2) NOT NULL,
    due_date DATE NOT NULL,
    recurring ENUM('Monthly', 'Weekly', 'Yearly', 'One-time') NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES user(user_id) ON DELETE CASCADE
);

